import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { MainLayout } from "@/components/layout/main-layout";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { ThemeProvider } from "@/components/providers/theme-provider";
import AuthProvider from "@/components/providers/auth-provider";
// import { Toaster } from "sonner";
import { Toaster } from "@/components/ui/sonner";
import Script from "next/script";
// import { after } from "next/server";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Title Seeker",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  // Secondary task
  // after(() => {
  //   console.log("TEST AFTER");
  // });

  return (
    <html lang={locale}>
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Script src="https://unpkg.com/react-scan/dist/auto.global.js" async /> */}
        <ThemeProvider>
          <NextIntlClientProvider messages={messages}>
            <AuthProvider>
              <MainLayout>{children}</MainLayout>
            </AuthProvider>
          </NextIntlClientProvider>
        </ThemeProvider>

        <Toaster richColors />
      </body>
    </html>
  );
}
