name: Title Seeker Frontend

# on:
#   push:
#     branches:
#       - main
on:
  push:
    tags:
      - "v*"

env:
  DOCKER_LOGIN: azalor
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  IMAGE_NAME: azalor/title-hunter-frontend

jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install yarn
        # Flag --legacy-peer-deps is used to resolve dependency between next-auth and react 19
        run: npm install yarn --legacy-peer-deps
      - name: install packages
        run: yarn
      - name: generate api client
        run: yarn gen-api
      - name: check types
        run: yarn type-check
      - name: check lint
        run: yarn lint
      - name: Run tests (Vitest)
        run: yarn test
  build:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            latest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_LOGIN }}
          password: ${{ env.DOCKER_ACCESS_TOKEN }}
      - name: Build and Push backend image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: update compose file
  #       uses: appleboy/scp-action@v0.1.4
  #       with:
  #         host: ${{ secrets.STAGE_HOST }}
  #         username: ${{ secrets.STAGE_USERNAME }}
  #         key: "${{ secrets.STAGE_SSH_KEY }}"
  #         port: ${{ secrets.STAGE_PORT }}
  #         source: docker-compose.stage.yaml
  #         target: ~/kraftjar_web/kraftjar-website
  #     - name: Deploy to stage
  #       uses: appleboy/ssh-action@v0.1.10
  #       with:
  #         host: ${{ secrets.STAGE_HOST }}
  #         username: ${{ secrets.STAGE_USERNAME }}
  #         key: ${{ secrets.STAGE_SSH_KEY }}
  #         port: ${{ secrets.STAGE_PORT }}
  #         script: |
  #           cd ~/kraftjar_web/kraftjar-website &&
  #           mv docker-compose.stage.yaml docker-compose.yml &&
  #           docker compose pull &&
  #           docker compose up -d
